
package br.com.ghc.back.rest.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebMethodService", targetNamespace = "http://service.ws.soap.back.gch.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebMethodService {


    /**
     * 
     * @param cpf
     * @param codCia
     * @param dataNacimento
     * @return
     *     returns br.com.ghc.back.rest.ws.Usuario
     */
    @WebMethod(operationName = "BuscarUsuario")
    @WebResult(name = "usuario", targetNamespace = "")
    @RequestWrapper(localName = "BuscarUsuario", targetNamespace = "http://service.ws.soap.back.gch.com.br/", className = "br.com.ghc.back.rest.ws.BuscarUsuario")
    @ResponseWrapper(localName = "BuscarUsuarioResponse", targetNamespace = "http://service.ws.soap.back.gch.com.br/", className = "br.com.ghc.back.rest.ws.BuscarUsuarioResponse")
    public Usuario buscarUsuario(
        @WebParam(name = "codCia", targetNamespace = "")
        String codCia,
        @WebParam(name = "cpf", targetNamespace = "")
        String cpf,
        @WebParam(name = "dataNacimento", targetNamespace = "")
        XMLGregorianCalendar dataNacimento);

}
